### PR TITLE
Compare bug fix

### PR DESCRIPTION
**Pull request by lazyWombat**
Hi, I've fixed a two bugs:
- a NullReferenceException in EFRelationshipChecker
- an incorrect message when the length does not match for varchar strings

The first bug in particular is annoying since the comparison is terminated with an exception.

### CODE REVIEW

**Comment by JonPSmith** [comment]
Hi @lazyWombat,

Good stuff, but no unit tests! Gota have unit tests. 

I can add these, but it won't be straight away.

**Comment by lazyWombat** [comment]
Took me a while to create a test for the NullReferenceException. The tests are not exactly isolated :) But I fix a typo along the way.

**Comment by JonPSmith** [comment]
Good stuff @lazyWombat ! Yep, the tests for the EfSchemaCompare are quite complex. 

Can you summerise what the two problems where. Looks like in one I didn't test the string length properly, but what was the foreign key reference about?

**Comment by lazyWombat** [comment]
No, in all cases the checks were correct. The error generation had some bugs though:

- Typo in the word "cascade". You use "casca**s**e"
- Incorrect sql length is reported in the error message. If you run the new test you well see that the reported error was something like "MaxLength does not match: Ef reports 20, Sql reports 20".
- And finally the reason I did the bug fixing: NullReference exception when ZeroOrOne-to-One relationship has cascade delete mismatch. You correctly checked foreignKey2 in the condition but when generating the error message you used foreignKey1 (which could be null) and that triggers a NullReferenceException.

**Comment by JonPSmith** [comment]
Thanks for your fixes - its an old library so I wouldn't normally support it so you doing it was good.

I have merged your changes, but I'm not going to release a new NuGet version as its very old. I assume you have your own version.

**Pull request merged**
